apiVersion: v1
kind: ReplicationController
metadata:
   name: myreplica
spec:
   replicas: 2
   selector:
      myname: sumeet
   template:
      metadata:
        name: testpod
        labels:
        myname: sumeet
      spec:
        containers:
        - name: c00
          image: nginx